### ISSUE TITLE
ข้อมูลผู้ป่วยไม่ถูกต้อง

### ISSUE THREAD

**Issue by narijitp** [patjawat/tcds#10]
เพศไม่ถูกต้อง และข้อมูลแพทย์ไม่แสดง
![การเลือก_006](https://user-images.githubusercontent.com/16026650/62036268-b01c0c00-b21b-11e9-86c9-18046d9ce792.png)

**Comment by suchartbu** [comment]
ปรับแก้ไขเรียบร้อยแล้ว
![ภาพหน้าจอจากเมื่อ 2019-08-05 17-22-32](https://user-images.githubusercontent.com/11677138/62457780-abb89b80-b7a5-11e9-8385-fb579cc0e139.png)
