### ISSUE TITLE
ระบบจัดจ่ายยา

### ISSUE THREAD

**Issue by suchartbu** [patjawat/tcds#14]
รายละเอียดตามเอกสารเมนูห้องจ่ายยา
https://docs.google.com/spreadsheets/d/1DrOAJztxqb0xWI5ay6Soa4cz7Pxvn_7abudJVBJ0jyI/edit#gid=569255986

**Comment by patjawat** [comment]
Update เรียบร้อย

<img width="1418" alt="จัดยา" src="https://user-images.githubusercontent.com/9455617/63591433-fecd8380-c5d8-11e9-8dc2-a1e9ec63357b.png">
