### ISSUE TITLE
ขอให้แสดงข้อความแจ้งความผิดพลาดเมื่อ API บันทึกข้อมูลในตาราง his_... ไม่ได้

### ISSUE THREAD

**Issue by suchartbu** [patjawat/tcds#17]
เมื่อมีการปรับโครงสร้างฐานข้อมูลใหม่ ทำให้ API ไม่สามารถบันทึกข้อมูลได้ เช่นตารางข้อมูลไม่มีเป็นต้น ไม่มีข้อมูลแจ้งกลับว่าเกิดจากอะไร?

**Comment by patjawat** [comment]
ทำการแก้ไขโดยเพิ่มเมนูให้สามารถตั้งค่าได้เอง

![Screen Shot 2562-08-06 at 21 21 17](https://user-images.githubusercontent.com/9455617/62548160-8d7b9a00-b890-11e9-84c3-90be48111f3a.png)
