### ISSUE TITLE
ไม่แสดง Requester ผู้บันทึกที่หน้า VITAL SIGNS CONTOUR OF PATIENT

### ISSUE THREAD

**Issue by suchartbu** [patjawat/tcds#18]
![ภาพหน้าจอจากเมื่อ 2019-08-05 18-13-10](https://user-images.githubusercontent.com/11677138/62460698-eb36b600-b7ac-11e9-9955-50c3ec345b03.png)

**Comment by patjawat** [comment]
แก้ไขเรียบร้อย

![m](https://user-images.githubusercontent.com/9455617/62547607-adf72480-b88f-11e9-8fed-1bf87de3999e.png)
