### ISSUE TITLE
เอกสารจาก hims แสดงไม่ครบ

### ISSUE THREAD

**Issue by narijitp** [patjawat/tcds#21]
![ภาพหน้าจอจากเมื่อ 2019-08-07 18-50-02](https://user-images.githubusercontent.com/16026650/62620996-eb69b980-b944-11e9-9aa6-c3e3f99bbbde.png)

**Comment by patjawat** [comment]
แก้ไขเรียบร้อยครับ
<img width="981" alt="Screen Shot 2562-08-21 at 17 00 28" src="https://user-images.githubusercontent.com/9455617/63422979-98f4c680-c435-11e9-94f9-6694f7f9b433.png">
