### ISSUE TITLE
ขอเพิ่มจำนวนเอกสารว่ามีเท่าไหร่

### ISSUE THREAD

**Issue by narijitp** [patjawat/tcds#22]
ตัวอย่างเช่น 
| All (40) | DOCTOR RECORD (20) | เอกสาร (ไม่ระบุชนิด) (10) | Order Sheet (10) |

![ภาพหน้าจอจากเมื่อ 2019-08-07 18-52-08](https://user-images.githubusercontent.com/16026650/62621582-71d2cb00-b946-11e9-8410-30f89047f1ae.png)

**Comment by patjawat** [comment]
Update เรียบร้อยครับ

<img width="1364" alt="EMR" src="https://user-images.githubusercontent.com/9455617/63591269-751db600-c5d8-11e9-9329-5426f787dee0.png">
