### ISSUE TITLE
upload เอกสารอื่น ๆ แล้ว พอจะอัพโหลดเพิ่มกลับไม่มีขึ้นให้เลือกเอกสาร

### ISSUE THREAD

**Issue by narijitp** [patjawat/tcds#23]
![ภาพหน้าจอจากเมื่อ 2019-08-07 19-01-51](https://user-images.githubusercontent.com/16026650/62621862-24a32900-b947-11e9-938c-43cf8acf3112.png)

**Comment by patjawat** [comment]
แก้ไขเรียบร้อย

<img width="1532" alt="Screen Shot 2562-08-22 at 17 49 58" src="https://user-images.githubusercontent.com/9455617/63510054-cf027b00-c507-11e9-9558-9ed7ae0e0de6.png">
