### ISSUE TITLE
ผู้ป่วยที่มาหา 2 VN ในหน่วยงานเดียวกัน พอเลือกรายการเพื่อจะเข้ามาบันทึกข้อมูลแล้ว error

### ISSUE THREAD

**Issue by narijitp** [patjawat/tcds#26]
![ภาพหน้าจอจากเมื่อ 2019-08-08 09-29-54](https://user-images.githubusercontent.com/16026650/62670932-2b6d8280-b9bf-11e9-9502-27ede3449321.png)
![ภาพหน้าจอจากเมื่อ 2019-08-08 09-28-05](https://user-images.githubusercontent.com/16026650/62670936-2e687300-b9bf-11e9-9120-38d42119f22d.png)

**Comment by suchartbu** [comment]
ทดสอบสามารถเลือกผู้ป่วยโดยไม่พบ Error แล้ว
![ภาพหน้าจอจากเมื่อ 2019-08-21 18-48-21](https://user-images.githubusercontent.com/11677138/63429469-571f4c80-c444-11e9-8985-2dc196639f44.png)
