### ISSUE TITLE
วันนี้หน้าที่คีย์ในแท็บ patient data ตอนเรียก HN. ครั้งแรกแล้วบันทึกมันจะหายไปเลยไม่บันทึกให้

### ISSUE THREAD

**Issue by narijitp** [patjawat/tcds#28]
วันนี้หน้าที่คีย์ในแท็บ patient data ตอนเรียก HN. ครั้งแรกแล้วกดบันทึกมันจะหายไปเลยไม่บันทึกให้ ต้องใส่ข้อมูลและกดบันทึกใหม่ถึงจะขึ้นให้ใส่ requester วันนี้เป็นทุก HN. เลยค่ะ

**Comment by patjawat** [comment]
แก้ไขเรียบร้อย เปลี่ยนตำแหน่ง ที่ redirect

Edit File tcds/modules/opdvisit/controllers/OpdVisitController.php

<img width="1552" alt="Screen Shot 2562-08-22 at 15 46 14" src="https://user-images.githubusercontent.com/9455617/63500651-72e22b80-c4f4-11e9-8eb6-e86f01a20926.png">
