### ISSUE TITLE
ไฟล์เอกสาร QR Code ที่สแกนไม่แสดงที่หน้าเอกสาร emr

### ISSUE THREAD

**Issue by narijitp** [patjawat/tcds#31]
![ภาพหน้าจอจากเมื่อ 2019-08-15 10-41-50](https://user-images.githubusercontent.com/16026650/63071420-6a648080-bf49-11e9-874d-c471057ce6f7.png)

**Comment by patjawat** [comment]
แก้ไขเรียบร้อย
<img width="1532" alt="Screen Shot 2562-08-22 at 17 49 58" src="https://user-images.githubusercontent.com/9455617/63509102-86e25900-c505-11e9-9497-5ddc9aa02a69.png">
