### ISSUE TITLE
ค้นหา Username เกิด Error

### ISSUE THREAD

**Issue by suchartbu** [patjawat/tcds#34]
Error
![ภาพหน้าจอจากเมื่อ 2019-08-20 11-03-15](https://user-images.githubusercontent.com/11677138/63316789-62865100-c33a-11e9-9a98-708995f1205e.png)
ค้นหาที่ Username
![ภาพหน้าจอจากเมื่อ 2019-08-20 11-04-31](https://user-images.githubusercontent.com/11677138/63316797-6b772280-c33a-11e9-8817-9f09f35ca99a.png)

**Comment by patjawat** [comment]
แก้ไขเรียบร้อยครับ

Edit File ==> tcds/modules/usermanager/models/UserSearch.php

<img width="1098" alt="Screen Shot 2562-08-22 at 14 27 16" src="https://user-images.githubusercontent.com/9455617/63494916-fb5acf00-c4e8-11e9-8677-12c45075c708.png">

==============================================
<img width="1552" alt="Screen Shot 2562-08-22 at 15 25 43" src="https://user-images.githubusercontent.com/9455617/63499299-c606af00-c4f1-11e9-921b-b8c5bde67e39.png">
