### ISSUE TITLE
เมื่อเลือก LAB ที่เมนูหลักขอให้เปิดเป็นแท็บใหม่เหมือน PACS

### ISSUE THREAD

**Issue by suchartbu** [patjawat/tcds#35]
ขอเป็นแท็บใหม่โครงสร้างหน้าเหมือน PACS
![ภาพหน้าจอจากเมื่อ 2019-08-20 11-20-51](https://user-images.githubusercontent.com/11677138/63317321-95314900-c33c-11e9-8fdc-cdde7f733c6a.png)

**Comment by patjawat** [comment]
แก้ไขเรียบร้อยครับ
<img width="1290" alt="Screen Shot 2562-08-22 at 15 20 45" src="https://user-images.githubusercontent.com/9455617/63498779-c6527a80-c4f0-11e9-89f0-4b60de84db84.png">
