### ISSUE TITLE
ขอให้แสดง VN. จาก HIMS เพื่อใช้งานในการอ้างถึงข้อมูลที่เชื่อมกัน

### ISSUE THREAD

**Issue by suchartbu** [patjawat/tcds#4]
![การเลือก_035](https://user-images.githubusercontent.com/11677138/62001980-a57f4b00-b125-11e9-96f3-86976e1cc6ff.png)

**Comment by patjawat** [comment]
แก้ไขเรียบร้อย

![Screen Shot 2562-08-06 at 21 34 08](https://user-images.githubusercontent.com/9455617/62549022-f6174680-b891-11e9-9b8a-57c35b1db79e.png)
