### ISSUE TITLE
โปรแกรมไม่ดึงไฟล์ QR Code ที่วางไว้ในโฟลเดอร์ /var/www/mount/ttr-scan-files

### ISSUE THREAD

**Issue by suchartbu** [patjawat/tcds#7]
![1563880052815 remmina-2019-7-28-4:20:52 579269](https://user-images.githubusercontent.com/11677138/62002252-50920380-b12a-11e9-8478-d7dbf0029345.png)

**Comment by patjawat** [comment]
แก้ไขเรียบร้อย

**Comment by narijitp** [comment]
วันนี้มันไม่ดูดไฟล์ค่ะ
![ภาพหน้าจอจากเมื่อ 2019-08-08 13-13-05](https://user-images.githubusercontent.com/16026650/62679349-63d08900-b9de-11e9-80ce-4f618a483453.png)

**Comment by patjawat** [comment]
แก้ไข update file  ใหม่เรียบร้อยแล้วนะครับ
