### ISSUE TITLE
โหลด Document Barcode ค้างที่หน้า Loading, please wait.

### ISSUE THREAD

**Issue by suchartbu** [patjawat/tcds#8]
![ภาพหน้าจอจากเมื่อ 2019-07-28 13-01-32](https://user-images.githubusercontent.com/11677138/62002931-21828e80-b138-11e9-83c9-9600f56e2c24.png)

**Comment by patjawat** [comment]
##### . API ไม่ทำงานวิธีการสั่ง run จะอยู่ที่
/var/www/html/tcds/python_api
./run_api.sh
=======================
##### . การ stop 
./stop_api.sh

**Comment by narijitp** [comment]
รันแล้วค่ะ แต่ยังไม่ได้เลย 
![ภาพหน้าจอจากเมื่อ 2019-07-29 15-57-46](https://user-images.githubusercontent.com/16026650/62035611-667ef180-b21a-11e9-9ef9-90b257a1a685.png)
![ภาพหน้าจอจากเมื่อ 2019-07-29 16-02-46](https://user-images.githubusercontent.com/16026650/62035622-6aab0f00-b21a-11e9-879c-eeade1ad0f75.png)

**Comment by patjawat** [comment]
แก้ไขเรียบร้อย
